### ISSUE TITLE
Getting result of a query in a data frame in R

### ISSUE THREAD

**Issue by mau5lives** [qubole/qds-sdk-R#2]
Hi,

I am trying to get the result of a hive command in a data frame in R using the qds package.

results<-qds::quboleHiveCommand(query="show tables" ,api_token='xxx')

But instead of getting the result of my query in 'results' , i just get the output of my query in the R console.
Is there any way to get the result set of the query in a data frame??

Thanks
Japneesh Singh

**Comment by karandeep-johar** [comment]
I had made the changes to this code. But I didn't repush the code again. You have to make changes in quboleHiveCommand.R file. instead of cat(results) just do return results. You can look at it here. https://github.com/KarandeepJohar/qds-sdk-R-1. Sorry about that.

**Comment by psychicindian** [comment]
This is fixed in the latest implementation of qubole r-sdk

**Comment by venciso** [comment]
Hi, 
On quboleHiveCommand.R I still see:
cat(results)

so I cannot load results into a data frame. 
Could you push this change please?
